version: '3'
services:
  iris:
    build: 
      context: .
    command: --check-caps false
    ports: 
      - 8080:52773
    volumes:
      - ./:/irisdev/app
      - /irisdev/app/ng/app/node_modules